apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-api
  template:
    metadata:
      labels:
        app: custom-api
    spec:
      containers:
      - name: custom-api
        image: your-docker-repo/custom-api:latest
        ports:
        - containerPort: 3000